void population () {
  buttonX1 = width*1/4;
  buttonY1 = height*3/4;
  buttonWidth1 = width*1/5;
  buttonHeight1 = height*1/5;
  buttonX2 = width*3/4;
  buttonY2 = height*3/4;
  buttonWidth2 = buttonWidth1;
  buttonHeight2 = buttonHeight1;
  rectDisplayX = width*1/8;
  rectDisplayY = height*1/8;
  rectDisplayWidth = buttonWidth1;
  rectDisplayHeight = buttonWidth1;
  sideX1 = width*1/4;
  sideY1 = height*3/4; 
  sideX2 = width*2/4;
  sideY2 = height*1/2;
  sideX3 = width*2/4;
  sideY3 = height*3/4;
} //End population
